services:
  wfm-awx-fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wfm-awx-fastapi
    ports:
      - "8070:8070"
    volumes:
      - ./:/app
      - ../ansible:/ansible
    command: uvicorn main:app --host 0.0.0.0 --port 8070
    restart: always
