---
- name: Configure Storage vSwitch, PortGroups, VMkernel
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX or chained from previous steps
    # mgmt_ip from Step 12 which is the host now
    # install_hostname from Step 12 which is username
    # root_password from Step 12
    esxi_hostname: "{{ management_ip }}"
    esxi_username: "{{ hostname }}"
    esxi_password: "{{ password }}"
    switch_name: "{{ storage_vswitch }}"
    nic_list: "{{ storage_uplinks }}"
    pg_name: "{{ portgroup_name }}"
    vlan_number: "{{ storage_vlan_id }}"
    storage_address: "{{ storage_ip_address }}"
    storage_mask: "{{ netmask }}"

  tasks:
    - name: "Validate required runtime parameters"
      fail:
        msg: "Missing required parameter: {{ item }}"
      when: vars[item] is not defined or vars[item] == ''
      loop:
        - esxi_hostname
        - esxi_password
        - storage_address

    - name: Validate uplink NICs list
      fail:
        msg: "Storage uplink NICs list cannot be empty"
      when: nic_list is not defined or nic_list | length == 0

    - name: Configure Storage vSwitch
      community.vmware.vmware_vswitch:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        switch: "{{ switch_name }}"
        nics: "{{ nic_list }}"
        state: present
      delegate_to: localhost
      register: vswitch_result

    - name: Ensure Storage portgroup exists
      community.vmware.vmware_portgroup:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        hosts: ["{{ esxi_hostname }}"]
        switch: "{{ switch_name }}"
        portgroup: "{{ pg_name }}"
        vlan_id: "{{ vlan_number | default(0) }}"
        state: present
      delegate_to: localhost
      register: portgroup_result

    - name: Create/Update Storage VMkernel (assign your Storage IP)
      community.vmware.vmware_vmkernel:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        vswitch_name: "{{ switch_name }}"
        portgroup_name: "{{ pg_name }}"
        network:
          type: static
          ip_address: "{{ storage_address }}"
          subnet_mask: "{{ storage_mask }}"
        state: present
      delegate_to: localhost
      register: vmkernel_result

    - name: "Show Storage vSwitch configuration result"
      debug:
        msg: "✅ Storage vSwitch '{{ stor_vswitch_name }}' configured with portgroup '{{ stor_portgroup }}' and VMkernel IP {{ stor_ip }}"

    - name: "Standardized output"
      set_fact:
        workflow_results:
          storage_vswitch:
            esxi_host: "{{ esxi_hostname }}"
            vswitch_name: "{{ switch_name }}"
            uplink_nics: "{{ nic_list }}"
            portgroup_name: "{{ pg_name }}"
            vlan_id: "{{ vlan_number }}"
            storage_ip: "{{ storage_address }}"
            storage_netmask: "{{ storage_mask }}"
            vswitch_changed: "{{ vswitch_result.changed }}"
            portgroup_changed: "{{ portgroup_result.changed }}"
            vmkernel_changed: "{{ vmkernel_result.changed }}"
            job_type: "configure_storage_vswitch"
            status: "success"
            timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display results
      debug:
        msg: "Storage networking configured on {{ esxi_hostname }}: vSwitch '{{ switch_name }}' with portgroup '{{ pg_name }}' (VLAN {{ vlan_number }}) and VMkernel IP {{ storage_address }}/{{ storage_mask }}"
