---
- name: OS Install in Intersight
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX
    org_moid: "{{ organization_moid }}"
    srvr_moid: "{{ server_moid }}"
    srvr_object_type: "{{ server_object_type }}"
    os_img_moid: "{{ os_image_moid }}"
    scu_img_moid: "{{ scu_image_moid }}"
    cnfg_file_moid: "{{ config_file_moid }}"
    hostname: "{{ username }}"
    passwd: "{{ password }}"
    dns_primary_address: "{{ dns_primary }}"
    mgmnt_ip: "{{ management_ip }}"
    mgmnt_netmask: "{{ management_netmask }}"
    mgmnt_gw: "{{ management_gateway }}"

  tasks:
    - name: "Debug variable values"
      debug:
        msg: |
          Variable values retrieved:
          =========================
          org_moid: {{ org_moid }}
          srvr_moid: {{ srvr_moid }}
          srvr_object_type: {{ srvr_object_type }}
          os_img_moid: {{ os_img_moid }}
          scu_img_moid: {{ scu_img_moid }}
          cnfg_file_moid: {{ cnfg_file_moid }}
          hostname: {{ hostname }}
          password: {{ passwd }}
          dns_primary_address: {{ dns_primary_address }}
          management_ip: {{ mgmnt_ip }}
          management_netmask: {{ mgmnt_netmask }}
          management_gw: {{ mgmnt_gw }}

          Raw step variables (if available):
          ==================================
          steps.step1.organization_moid: {{ steps.step1.organization_moid | default('NOT_SET') }}
          steps.step4.server_profile_moid: {{ steps.step4.server_profile_moid | default('NOT_SET') }}
          steps.step8.os_image.moid: {{ steps.step8.os_image.moid | default('NOT_SET') }}
          steps.step9.os_config_file.moid: {{ steps.step9.os_config_file.moid | default('NOT_SET') }}
          steps.step10.scu_image.moid: {{ steps.step10.scu_image.moid | default('NOT_SET') }}

    - name: "Validate required runtime parameters"
      fail:
        msg: "Required parameters missing. Pass all required moids and network configuration via -e flags"
      when: >
        org_moid is not defined or org_moid == "" or
        srvr_moid is not defined or srvr_moid == "" or
        srvr_object_type is not defined or srvr_object_type == "" or
        os_img_moid is not defined or os_img_moid == "" or
        cnfg_file_moid is not defined or cnfg_file_moid == "" or
        scu_img_moid is not defined or scu_img_moid == "" or
        hostname is not defined or hostname == "" or
        passwd is not defined or passwd == "" or
        dns_primary_address is not defined or dns_primary_address == "" or
        mgmnt_ip is not defined or mgmnt_ip == "" or
        mgmnt_netmask is not defined or mgmnt_netmask == "" or
        mgmnt_gw is not defined or mgmnt_gw == ""
    - name: Trigger OS Install
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        api_uri: "{{ intersight_base_url }}"
        resource_path: "/os/Installs"
        update_method: post
        api_body:
          Description: "Performing OS Install through Ansible Code"
          InstallMethod: "vMedia"
          Image:
            ObjectType: "softwarerepository.OperatingSystemFile"
            Moid: "{{ os_img_moid }}"
          OsduImage:
            ObjectType: "firmware.ServerConfigurationUtilityDistributable"
            Moid: "{{ scu_img_moid }}"
          OverrideSecureBoot: true
          Organization:
            ObjectType: "organization.Organization"
            Moid: "{{ org_moid }}"
          Server:
            ObjectType: "{{ srvr_object_type }}"
            Moid: "{{ srvr_moid }}"
          ConfigurationFile:
            ObjectType: "os.ConfigurationFile"
            Moid: "{{ cnfg_file_moid }}"
          AdditionalParameters: null
          Answers:
            Hostname: "{{ hostname }}"
            IpConfigType: "static"
            RootPassword: "{{ passwd }}"
            IsRootPasswordCrypted: false
            Nameserver: "{{ dns_primary_address }}"
            Source: "Template"
            IpConfiguration:
              ObjectType: "os.Ipv4Configuration"
              IpV4Config:
                IpAddress: "{{ mgmnt_ip }}"
                Netmask: "{{ mgmnt_netmask }}"
                Gateway: "{{ mgmnt_gw }}"
          InstallTarget:
            ObjectType: "os.VirtualDrive"
            Name: "MStorBootVd"
            StorageControllerSlotId: "MSTOR-RAID"
            Id: "0"
      register: install_resp

    - name: Show OS install response
      debug:
        var: install_resp.api_response

    - name: "Standardized output"
      set_fact:
        workflow_results:
          os_installation:
            install_moid: "{{ install_resp.api_response.Moid | default('unknown') }}"
            moid: "{{ srvr_moid }}"
            hostname: "{{ hostname }}"
            management_ip: "{{ mgmnt_ip }}"
            install_status: "{{ install_resp.api_response.InstallState | default('initiated') }}"
            data: "{{ install_resp }}"
            job_type: "os_install"
            status: "success"
            password: "{{ passwd }}"
