---
- name: Reserve available IP and DNS in Infoblox
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ticket.yml

  tasks:
    - name: Encode credentials
      set_fact:
        ipam_auth_header: "Basic {{ (infoblox_username + ':' + infoblox_password) | b64encode }}"

    - name: Reserve IP and DNS from selected network (Infoblox)
      uri:
        url: "{{ infoblox_api_url }}/record:host"
        method: POST
        headers:
          Authorization: "{{ ipam_auth_header }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ reserve_ip_dns_input.hostname }}{{ reserve_ip_dns_input.dns_zone }}"
          comment: "{{ reserve_ip_dns_input.host_comment | default('Created by Ansible automation') }}"
          ipv4addrs:
            - ipv4addr: "{{ fetch_ip_output.available_ip }}"
        validate_certs: false
        return_content: true
        timeout: 30
      register: host_response
      failed_when: host_response.status != 201
      retries: 2
      delay: 3
