---
- name: Reserve available IP in Infoblox
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX or chained from fetch_available_ip.yml
    reservation_name: "{{ ip_reservation_name }}"
    ip_address: "{{  ip_address_to_reserve }}"
    comment: "{{ default('Reserved via automation') }}"
    match_client: "{{ default('RESERVED') }}"
    api_url: "{{ infoblox_api_url  }}"
    api_timeout: "{{ default(30) }}"

  tasks:
    - name: "Validate required runtime parameters"
      fail:
        msg: "Required parameters missing. Pass: -e 'name=ReservationName available_ip=10.50.1.4'"
      when: >
        reservation_name is not defined or reservation_name == "" or
        ip_address is not defined or ip_address == ""
    - name: Encode credentials
      set_fact:
        ipam_auth_header: "Basic {{ (infoblox_username + ':' + infoblox_password) | b64encode }}"

    - name: Reserve IP from selected network (Infoblox)
      uri:
        url: "{{ infoblox_api_url }}/fixedaddress"
        method: POST
        headers:
          Authorization: "{{ ipam_auth_header }}"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "{{ reservation_name }}"
          ipv4addr: "{{ ip_to_reserve | default(ip_address) }}"
          comment: "{{ comment }}"
          match_client: "{{ match_client }}"
        validate_certs: false
        return_content: true
        timeout: 30
      register: ip_response
      failed_when: ip_response.status != 201

    - name: "Show reservation details"
      debug:
        msg: "✅ Reserved IP {{ ip_to_reserve | default(ip_address) }} with name '{{ reservation_name }}' Ip address {{ ip_address}} "

    - name: "Standardized output"
      set_fact:
        workflow_results:
          ip_reservation:
            name: "{{ reservation_name }}"
            reserved_ip: "{{ ip_to_reserve | default(ip_address) }}"
            comment: "{{ comment }}"
            reservation_ref: "{{ ip_response.json if ip_response.json is string else ip_response.json | string }}"
            data: "{{ ip_response }}"
            job_type: "reserve_available_ip"
            status: "success"
