---
- name: Configure Management vSwitch
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX
    esxi_hostname: "{{ mgmt_ip }}"
    esxi_username: "{{ esxi_username }}"
    esxi_password: "{{ esxi_password }}"
    vswitch_name: "{{ vswitch_name }}"
    uplink_nics: "{{ uplink_nics }}"
  

  tasks:
    - name: Ensure Mgmt vSwitch has vmnic0 + vmnic1 (mgmt-A/mgmt-B)
      community.vmware.vmware_vswitch:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        switch: "{{ vswitch_name }}"
        nics: "{{ uplink_nics }}"
        state: present
      delegate_to: localhost
      register: vswitch_result

    - name: Set standard output
      set_fact:
        # Legacy compatibility
        mgmt_vswitch_result: "{{ vswitch_result }}"
        # Standard output structure
        workflow_results:
          mgmt_vswitch:
            esxi_host: "{{ esxi_hostname }}"
            vswitch_name: "{{ vswitch_name }}"
            uplink_nics: "{{ uplink_nics }}"
            changed: "{{ vswitch_result.changed }}"
            job_type: "configure_mgmt_vswitch"
            status: "{{ 'success' if not vswitch_result.failed else 'failed' }}"
            timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display results
      debug:
        msg: "Management vSwitch '{{ vswitch_name }}' configured on {{ esxi_hostname }} with uplinks: {{ uplink_nics | join(', ') }}{{ ' (changed)' if vswitch_result.changed else ' (no changes needed)' }}"
