---
- name: Configure Management vSwitch
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX or chained from previous steps
    # mgmt_ip from Step 12 which is the host now
    # install_hostname from Step 12 which is username
    # root_password from Step 12
    esxi_hostname: "{{ steps.step12.mgmt_ip | default(mgmt_ip) | default('') }}"
    esxi_username: "{{ steps.step12.install_hostname | default(esxi_username) | default('root') }}"
    esxi_password: "{{ steps.step12.root_password | default(esxi_password) | default('') }}"
    switch_name: "{{ vswitch_name | default('vSwitch0') }}"
    nic_list: "{{ uplink_nics | default(['vmnic0', 'vmnic1']) }}"
  

  tasks:
    - name: Ensure Mgmt vSwitch has vmnic0 + vmnic1 (mgmt-A/mgmt-B)
      community.vmware.vmware_vswitch:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        switch: "{{ switch_name }}"
        nics: "{{ nic_list }}"
        state: present
      delegate_to: localhost
      register: vswitch_result

    - name: Set standard output
      set_fact:
        # Legacy compatibility
        mgmt_vswitch_result: "{{ vswitch_result }}"
        # Standard output structure
        workflow_results:
          mgmt_vswitch:
            esxi_host: "{{ esxi_hostname }}"
            vswitch_name: "{{ switch_name }}"
            uplink_nics: "{{ nic_list }}"
            changed: "{{ vswitch_result.changed }}"
            job_type: "configure_mgmt_vswitch"
            status: "{{ 'success' if not vswitch_result.failed else 'failed' }}"
            timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display results
      debug:
        msg: "Management vSwitch '{{ switch_name }}' configured on {{ esxi_hostname }} with uplinks: {{ nic_list | join(', ') }}{{ ' (changed)' if vswitch_result.changed else ' (no changes needed)' }}"
