---
- name: Configure Storage vSwitch, PortGroups, VMkernel
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX
    esxi_hostname: "{{ mgmt_ip }}"
    esxi_username: "{{ esxi_username }}"
    esxi_password: "{{ esxi_password }}"
    vswitch_name: "{{ storage_vswitch_name }}"
    uplink_nics: "{{ storage_uplink_nics }}"
    portgroup_name: "{{ storage_portgroup_name }}"
    vlan_id: "{{ storage_vlan_id }}"
    storage_ip: "{{ storage_ip_address }}"
    storage_netmask: "{{ storage_subnet_mask }}"

  tasks:
    - name: Validate required parameters
      fail:
        msg: "Missing required parameter: {{ item }}"
      when: vars[item] is not defined or vars[item] == ''
      loop:
        - esxi_hostname
        - esxi_password
        - storage_ip

    - name: Validate uplink NICs list
      fail:
        msg: "Storage uplink NICs list cannot be empty"
      when: uplink_nics is not defined or uplink_nics | length == 0

    - name: Configure Storage vSwitch
      community.vmware.vmware_vswitch:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        switch: "{{ vswitch_name }}"
        nics: "{{ uplink_nics }}"
        state: present
      delegate_to: localhost
      register: vswitch_result

    - name: Configure Storage Port Group
      community.vmware.vmware_portgroup:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        hosts: ["{{ esxi_hostname }}"]
        switch: "{{ vswitch_name }}"
        portgroup: "{{ portgroup_name }}"
        vlan_id: "{{ vlan_id | default(0) }}"
        state: present
      delegate_to: localhost
      register: portgroup_result

    - name: Configure Storage VMkernel Interface
      community.vmware.vmware_vmkernel:
        hostname: "{{ esxi_hostname }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_hostname }}"
        vswitch_name: "{{ vswitch_name }}"
        portgroup_name: "{{ portgroup_name }}"
        network:
          type: static
          ip_address: "{{ storage_ip }}"
          subnet_mask: "{{ storage_netmask }}"
        state: present
      delegate_to: localhost
      register: vmkernel_result

    - name: Set standard output
      set_fact:
        # Legacy compatibility
        storage_vswitch_result:
          vswitch: "{{ vswitch_result }}"
          portgroup: "{{ portgroup_result }}"
          vmkernel: "{{ vmkernel_result }}"
        # Standard output structure
        workflow_results:
          storage_vswitch:
            esxi_host: "{{ esxi_hostname }}"
            vswitch_name: "{{ vswitch_name }}"
            uplink_nics: "{{ uplink_nics }}"
            portgroup_name: "{{ portgroup_name }}"
            vlan_id: "{{ vlan_id }}"
            storage_ip: "{{ storage_ip }}"
            storage_netmask: "{{ storage_netmask }}"
            vswitch_changed: "{{ vswitch_result.changed }}"
            portgroup_changed: "{{ portgroup_result.changed }}"
            vmkernel_changed: "{{ vmkernel_result.changed }}"
            job_type: "configure_storage_vswitch"
            status: "success"
            timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display results
      debug:
        msg: "Storage networking configured on {{ esxi_hostname }}: vSwitch '{{ vswitch_name }}' with portgroup '{{ portgroup_name }}' (VLAN {{ vlan_id }}) and VMkernel IP {{ storage_ip }}/{{ storage_netmask }}"
