---
- name: Configure Storage vSwitch, PortGroups, VMkernel
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - must be passed via extra-vars
    # Required: esxi_host, esxi_username, esxi_password, storage_vswitch_name, storage_portgroup, storage_ip, storage_netmask
    # Optional: storage_uplinks, storage_vlan_id
    stor_vswitch_name: "{{ storage_vswitch_name }}"
    stor_uplinks: "{{ storage_uplinks | default(['vmnic2', 'vmnic3']) }}"
    stor_portgroup: "{{ storage_portgroup }}"
    stor_vlan_id: "{{ storage_vlan_id | default(0) }}"
    stor_ip: "{{ storage_ip }}"
    stor_netmask: "{{ storage_netmask }}"

  tasks:
    - name: "Validate required runtime parameters"
      fail:
        msg: "Required parameters missing. Need: esxi_host, esxi_username, esxi_password, storage_vswitch_name, storage_portgroup, storage_ip, storage_netmask"
      when: >
        esxi_host is not defined or esxi_host == "" or
        esxi_username is not defined or esxi_username == "" or
        esxi_password is not defined or esxi_password == "" or
        stor_vswitch_name is not defined or stor_vswitch_name == "" or
        stor_portgroup is not defined or stor_portgroup == "" or
        stor_ip is not defined or stor_ip == "" or
        stor_netmask is not defined or stor_netmask == ""
    - name: Ensure Storage vSwitch exists with specified uplinks
      community.vmware.vmware_vswitch:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_host }}"
        switch: "{{ stor_vswitch_name }}"
        nics: "{{ stor_uplinks }}"
        state: present
      delegate_to: localhost
      register: vswitch_result

    - name: Ensure Storage portgroup exists
      community.vmware.vmware_portgroup:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        hosts: ["{{ esxi_host }}"]
        switch: "{{ stor_vswitch_name }}"
        portgroup: "{{ stor_portgroup }}"
        vlan_id: "{{ stor_vlan_id }}"
        state: present
      delegate_to: localhost
      register: portgroup_result

    - name: Create/Update Storage VMkernel (assign your Storage IP)
      community.vmware.vmware_vmkernel:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_host }}"
        vswitch_name: "{{ stor_vswitch_name }}"
        portgroup_name: "{{ stor_portgroup }}"
        network:
          type: static
          ip_address: "{{ stor_ip }}"
          subnet_mask: "{{ stor_netmask }}"
        state: present
      delegate_to: localhost
      register: vmkernel_result

    - name: "Show Storage vSwitch configuration result"
      debug:
        msg: "✅ Storage vSwitch '{{ stor_vswitch_name }}' configured with portgroup '{{ stor_portgroup }}' and VMkernel IP {{ stor_ip }}"

    - name: "Standardized output"
      set_fact:
        workflow_results:
          storage_vswitch:
            esxi_host: "{{ esxi_host }}"
            vswitch_name: "{{ stor_vswitch_name }}"
            uplinks: "{{ stor_uplinks }}"
            portgroup: "{{ stor_portgroup }}"
            vlan_id: "{{ stor_vlan_id }}"
            vmkernel_ip: "{{ stor_ip }}"
            vmkernel_netmask: "{{ stor_netmask }}"
            vswitch_status: "{{ 'configured' if vswitch_result.changed else 'already_configured' }}"
            portgroup_status: "{{ 'configured' if portgroup_result.changed else 'already_configured' }}"
            vmkernel_status: "{{ 'configured' if vmkernel_result.changed else 'already_configured' }}"
            job_type: "configure_storage_vswitch"
            status: "success"
