---
- name: Configure Management vSwitch
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - must be passed via extra-vars
    # Required: esxi_host, esxi_username, esxi_password
    # Optional: vswitch_name (defaults to 'vSwitch0'), uplink_nics (defaults to ['vmnic0', 'vmnic1'])
    mgmt_vswitch_name: "{{ vswitch_name | default('vSwitch0') }}"
    mgmt_uplink_nics: "{{ uplink_nics | default(['vmnic0', 'vmnic1']) }}"

  tasks:
    - name: "Validate required runtime parameters"
      fail:
        msg: "Required parameters missing."
      when: >
        esxi_host is not defined or esxi_host == "" or
        esxi_username is not defined or esxi_username == "" or
        esxi_password is not defined or esxi_password == ""
    - name: Ensure Mgmt vSwitch has proper uplinks configured
      community.vmware.vmware_vswitch:
        hostname: "{{ esxi_host }}"
        username: "{{ esxi_username }}"
        password: "{{ esxi_password }}"
        validate_certs: false
        esxi_hostname: "{{ esxi_host }}"
        switch: "{{ mgmt_vswitch_name }}"
        nics: "{{ mgmt_uplink_nics }}"
        state: present
      delegate_to: localhost
      register: vswitch_result

    - name: "Show vSwitch configuration result"
      debug:
        msg: "✅ Management vSwitch '{{ mgmt_vswitch_name }}' configured with uplinks {{ mgmt_uplink_nics | join(', ') }}"

    - name: "Standardized output"
      set_fact:
        workflow_results:
          mgmt_vswitch:
            esxi_host: "{{ esxi_host }}"
            vswitch_name: "{{ mgmt_vswitch_name }}"
            uplink_nics: "{{ mgmt_uplink_nics }}"
            configuration_status: "{{ 'configured' if vswitch_result.changed else 'already_configured' }}"
            data: "{{ vswitch_result }}"
            job_type: "configure_mgmt_vswitch"
            status: "success"
