---
- name: Create Server Profiles
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - passed from previous steps or command line
    org_moid: "{{ organization_moid | default('') }}"
    pool_moid: "{{ resource_pool_moid | default('') }}"
    template_moid: "{{ server_profile_template_moid | default('') }}"
    profiles_to_create: "{{ server_profile_info | default([]) }}"

  vars:
    workflow_results: {}

  tasks:
    - name: Validate required parameters
      fail:
        msg: "Missing required parameter: {{ item }}"
      when: vars[item] is not defined or vars[item] == ''
      loop:
        - org_moid
        - pool_moid
        - template_moid

    - name: Validate server profile list
      fail:
        msg: "No server profiles specified to create"
      when: profiles_to_create | length == 0

    - name: Create Server Profiles from Template
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        api_uri: "{{ intersight_base_url }}"
        resource_path: /server/Profiles
        update_method: post
        api_body:
          Name: "{{ item.name }}"
          Description: "{{ item.description }}"
          TargetPlatform: "FIAttached"
          Type: "instance"
          ServerAssignmentMode: "Pool"
          SrcTemplate:
            ObjectType: "server.ProfileTemplate"
            Moid: "{{ template_moid }}"
          ServerPool:
            ObjectType: "resourcepool.Pool"
            Moid: "{{ pool_moid }}"
          Organization:
            ObjectType: "organization.Organization"
            Moid: "{{ org_moid }}"
          Tags:
            - Key: "configmode"
              Value: "ansible"
            - Key: "automation.timestamp"
              Value: "{{ ansible_date_time.iso8601 }}"
      loop: "{{ profiles_to_create }}"
      loop_control:
        label: "{{ item.name }}"
      register: server_profile_creation_result

    - name: "Standardized output"
      set_fact:
        workflow_results:
          server_profiles: "{{ server_profile_creation_result.results }}"

    - name: Summarize created profiles
      debug:
        msg: >-
          Profile {{ item.api_response.Name }} 
          (Moid: {{ item.api_response.Moid }}) 
          Assigned server: {{ item.api_response.AssignedServer.Moid | default('not yet assigned') }}
      loop: "{{ server_profile_creation_result.results }}"
