---
- name: Lookup Server Profile Template Moid Independently
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX
    template_name: "{{ server_profile_template_name | default('') }}"

  tasks:
    - name: Validate required parameters
      fail:
        msg: "Missing required parameter: server_profile_template_name"
      when: template_name is not defined or template_name == ''

    - name: Lookup Server Profile Template by Name
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        api_uri: "{{ intersight_base_url }}"
        resource_path: "/server/ProfileTemplates"
        query_params:
          $filter: "Name eq '{{ template_name }}'"
      register: template_lookup

    - name: Validate server profile template found
      fail:
        msg: "No server profile template found with name '{{ template_name }}'"
      when: template_lookup.api_response is not defined or template_lookup.api_response.Moid is not defined

    - name: Set standard output
      set_fact:
        # Legacy compatibility
        template_moid: "{{ template_lookup.api_response.Moid }}"
        server_profile_template_moid: "{{ template_lookup.api_response.Moid }}"
        # Standard output structure
        workflow_results:
          server_profile_template:
            name: "{{ template_name }}"
            moid: "{{ template_lookup.api_response.Moid | default('') }}"
            data: "{{ template_lookup.api_response | default({}) }}"
            job_type: "lookup_server_profile_template"
            status: "success"

    - name: Display results
      debug:
        msg: "Found server profile template '{{ template_name }}' with MOID: {{ template_lookup.api_response.Moid }}"
