---
- name: Lookup OS Configuration File Moid
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ticket.yml

  tasks:
    - name: Lookup SCU image MOID by name
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        resource_path: "/firmware/ServerConfigurationUtilityDistributables"
        query_params:
          $filter: "Name eq '{{ lookup_scu_image_input.scu_image_name }}'"
          $select: "Moid,Name"
      register: scu_lookup

    - debug:
        msg: "{{ scu_lookup.api_response.Moid }}"
