---
- name: Lookup Organization Moid Independently
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Default organization name - can be overridden at runtime
    default_org_name: "default"
    org_name: "{{ organization_name | default(default_org_name) }}"

  tasks:
    - name: "Lookup Organization Moid"
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        api_uri: "{{ intersight_base_url }}"
        resource_path: "/organization/Organizations"
        query_params:
          $filter: "Name eq '{{ org_name }}'"
      register: lookup_result

    - name: "Standardized output"
      set_fact:
        workflow_results:
          organization:
            name: "{{ org_name }}"
            moid: "{{ lookup_result.api_response.Moid | default('') }}"
            data: "{{ lookup_result.api_response | default({}) }}"
            job_type: "lookup_organization"
            status: "success"

    - name: "Check if organization exists"
      fail:
        msg: "No organization found with name '{{ org_name }}'"
      when: lookup_result.api_response is not defined or lookup_result.api_response | length == 0

    - name: "Set organization moid as fact"
      set_fact:
        organization_moid: "{{ lookup_result.api_response.Moid }}"

    - name: "Debug resolved organization moid"
      debug:
        msg: "Organization '{{ org_name }}' resolved to moid: {{ organization_moid }}"
