---
- name: Lookup OS Configuration File Moid
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ticket.yml

  tasks:
    - name: Lookup OS Configuration File by name
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        resource_path: "/os/ConfigurationFiles"
        query_params:
          $filter: "Name eq '{{ lookup_os_config_input.config_file_name }}'"
          $select: "Moid,Name"
      register: config_lookup

    - debug:
        msg: "{{ config_lookup.api_response.Moid }}"
