---
- name: Lookup Resource Pool Moid Independently
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX
    pool_name: "{{ resource_pool_name }}"

  tasks:
    - name: Validate required parameters
      fail:
        msg: "Missing required parameter: resource_pool_name"
      when: pool_name is not defined or pool_name == ''

    - name: "Lookup Resource Pool by Name"
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        api_uri: "{{ intersight_base_url }}"
        resource_path: "/resourcepool/Pools"
        query_params:
          $filter: "Name eq '{{ pool_name }}'"
      register: resource_pool_lookup

    - name: Validate resource pool found
      fail:
        msg: "No resource pool found with name '{{ pool_name }}'"
      when: resource_pool_lookup.api_response is not defined or resource_pool_lookup.api_response.Moid is not defined

    - name: Set standard output
      set_fact:
        resource_pool_moid: "{{ resource_pool_lookup.api_response.Moid }}"
        workflow_results:
          resource_pool:
            name: "{{ pool_name }}"
            moid: "{{ resource_pool_lookup.api_response.Moid | default('') }}"
            data: "{{ resource_pool_lookup.api_response | default({}) }}"
            job_type: "lookup_resource_pool"
            status: "success"

    - name: Display results
      debug:
        msg: "Found resource pool '{{ pool_name }}' with MOID: {{ resource_pool_lookup.api_response.Moid }}"
