---
- name: Check Server with Server Profiles Assigned
  hosts: localhost
  connection: local
  gather_facts: yes

  vars_files:
    - credentials.yml

  vars:
    # Runtime parameters - can be passed via -e or AWX or chained from previous steps
    profile_moid: "{{ steps.step4.server_profile_moid | default(server_profile_moid) | default('') }}"

  tasks:
    - name: Debug available variables for troubleshooting
      debug:
        msg:
          - "server_profile_moid: {{ server_profile_moid | default('NOT_SET') }}"
          - "workflow_job_output.server_profile_moid: {{ workflow_job_output.server_profile_moid | default('NOT_SET') }}"
          - "profile_moid: {{ profile_moid }}"
          - "hostvars keys: {{ hostvars.keys() | list }}"

    - name: Validate required parameters
      fail:
        msg: "Missing required parameter: server_profile_moid. Please pass via -e server_profile_moid=<value> or ensure previous workflow step outputs server_profile_moid"
      when: profile_moid is not defined or profile_moid == ''

    - name: Get profile details to check assigned server
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        api_uri: "{{ intersight_base_url }}"
        resource_path: "/server/Profiles"
        query_params:
          $filter: "Moid eq '{{ profile_moid }}'"
      register: profile_details

    - name: Validate profile found
      fail:
        msg: "Server profile with Moid {{ profile_moid }} not found"
      when: profile_details.api_response is not defined or profile_details.api_response.Moid is not defined

    - name: Determine server assignment status
      set_fact:
        assigned_server_moid: "{{ profile_details.api_response.AssignedServer.Moid if (profile_details.api_response.AssignedServer is defined and profile_details.api_response.AssignedServer.Moid is defined) else 'none' }}"
        assigned_server_object_type: "{{ profile_details.api_response.AssignedServer.ObjectType if (profile_details.api_response.AssignedServer is defined and profile_details.api_response.AssignedServer.ObjectType is defined) else 'none' }}"
        assignment_status: "{{ 'assigned' if (profile_details.api_response.AssignedServer is defined and profile_details.api_response.AssignedServer.Moid is defined) else 'unassigned' }}"

    - name: "Standardized output"
      set_fact:
        workflow_results:
          server_assignment:
            profile_name: "{{ profile_details.api_response.Name }}"
            server_moid: "{{ assigned_server_moid }}"
            server_object_type: "{{ assigned_server_object_type }}"
            assgnmnt_status: "{{ assignment_status }}"
            job_type: "lookup_server_with_server_profile"
            status: "success"
            timestamp: "{{ ansible_date_time.iso8601 }}"

    - name: Display results
      debug:
        msg: "Profile '{{ profile_details.api_response.Name }}' ({{ profile_moid }}) is {{ assignment_status }}{{ ' to server ' + assigned_server_moid if assignment_status == 'assigned' else '' }}"
