---
- name: OS Install in Intersight
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
    - ticket.yml

  tasks:
    - name: Trigger OS Install
      cisco.intersight.intersight_rest_api:
        api_key_id: "{{ intersight_api_key_id }}"
        api_private_key: "{{ intersight_api_private_key }}"
        resource_path: "/os/Installs"
        update_method: post
        api_body:
          Description: "Performing OS Install through Ansible Code"
          InstallMethod: "vMedia"
          Image:
            ObjectType: "softwarerepository.OperatingSystemFile"
            Moid: "{{ lookup_os_image_output.os_image_moid }}"
          OsduImage:
            ObjectType: "firmware.ServerConfigurationUtilityDistributable"
            Moid: "{{ lookup_scu_image_output.scu_image_moid }}"
          OverrideSecureBoot: true
          Organization:
            ObjectType: "organization.Organization"
            Moid: "{{ organization_output.organization_moid }}"
          Server:
            ObjectType: "{{ lookup_swsp_output.server_object_type }}"
            Moid: "{{ lookup_swsp_output.server_moid }}"
          ConfigurationFile:
            ObjectType: "os.ConfigurationFile"
            Moid: "{{ lookup_os_config_output.config_file_moid }}"
          AdditionalParameters: null
          Answers:
            Hostname: "{{ os_install_input.install_hostname }}"
            IpConfigType: "static"
            RootPassword: "{{ os_install_input.root_password }}"
            IsRootPasswordCrypted: false
            Nameserver: "{{ os_install_input.dns_primary }}"
            Source: "Template"
            IpConfiguration:
              ObjectType: "os.Ipv4Configuration"
              IpV4Config:
                IpAddress: "{{ os_install_input.mgmt_ip }}"
                Netmask: "{{ os_install_input.mgmt_netmask }}"
                Gateway: "{{ os_install_input.mgmt_gw }}"
          InstallTarget:
            ObjectType: "os.VirtualDrive"
            Name: "MStorBootVd"
            StorageControllerSlotId: "MSTOR-RAID"
            Id: "0"
      register: install_resp

    - name: Show OS install response
      debug:
        var: install_resp.api_response
