name: Deploy FastAPI with Docker Compose

on:
  push:
    branches:
      - dev
      - main
jobs:
  deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH key
        shell: bash
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      - name: Copy files to remote server
        shell: bash
        run: |
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no -r ./server/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:~/wfm-awx/server/

      - name: Run Docker Compose remotely
        shell: bash
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
            cd ~/wfm-awx/server
            if [ "${{ github.ref }}" = "refs/heads/main" ]; then
              # echo "${{ secrets.ENV_PROD }}" > .env.prod
              docker-compose -f docker-compose.yml up --build -d
            elif [ "${{ github.ref }}" = "refs/heads/dev" ]; then
              # echo "${{ secrets.ENV_DEV }}" > .env.dev
              docker-compose -f docker-compose.yml up --build -d
            fi
          EOF

      - name: Cleanup SSH key
        if: always()
        shell: bash
        run: |
          rm -f ~/.ssh/deploy_key
