name: Deploy to Staging and Production

on:
  push:
    branches:
      - dev
      - main

permissions:
  contents: read
  packages: read

jobs:
  deploy:
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Determine environment
        id: env
        shell: powershell
        run: |
          if ('${{ github.ref }}' -eq 'refs/heads/main') {
            [IO.File]::AppendAllText($env:GITHUB_OUTPUT, "ENV_NAME=Production`n")
            [IO.File]::AppendAllText($env:GITHUB_OUTPUT, "DEPLOY_PATH=~/wfm-awx/production`n")
          } else {
            [IO.File]::AppendAllText($env:GITHUB_OUTPUT, "ENV_NAME=Staging`n")
            [IO.File]::AppendAllText($env:GITHUB_OUTPUT, "DEPLOY_PATH=~/wfm-awx/staging`n")
          }

      - name: Package deploy payload
        shell: powershell
        run: |
          # Clean up previous deploy directory
          if (Test-Path ".deploy") {
            Remove-Item -Recurse -Force ".deploy"
          }
          New-Item -ItemType Directory -Force -Path ".deploy" | Out-Null

          # Copy entire project (server and ansible folders)
          Write-Host "Copying server folder..."
          Copy-Item -Path "server" -Destination ".deploy\server" -Recurse -Force

          Write-Host "Copying ansible folder..."
          Copy-Item -Path "ansible" -Destination ".deploy\ansible" -Recurse -Force

          # Copy project root files if any
          $rootFiles = @("README.md")
          foreach ($file in $rootFiles) {
            if (Test-Path $file) {
              Copy-Item -Path $file -Destination ".deploy\" -Force
            }
          }

          # Show what's being deployed
          Write-Host ""
          Write-Host "Project structure being deployed:"
          Get-ChildItem -Path ".deploy" -Recurse -Directory | Select-Object -First 10 | ForEach-Object {
            $relativePath = $_.FullName.Replace((Get-Item '.deploy').FullName, '')
            Write-Host "  - $relativePath"
          }

          # Create tar archive
          if (Test-Path "deploy.zip") {
            Remove-Item "deploy.zip" -Force
          }

          Write-Host ""
          Write-Host "Creating deployment archive..."
          tar -czf deploy.zip -C .deploy .

          # Show archive info
          $zipInfo = Get-Item "deploy.zip"
          Write-Host ""
          Write-Host "Deploy package created:"
          Write-Host "   Size: $([math]::Round($zipInfo.Length / 1KB, 2)) KB"

      - name: Prepare SSH key
        shell: powershell
        run: |
          $sshDir = Join-Path $env:USERPROFILE ".ssh"
          New-Item -ItemType Directory -Force -Path $sshDir | Out-Null

          $keyContent = '${{ secrets.SERVER_SSH_KEY }}'
          if (!$keyContent) {
            Write-Error "SERVER_SSH_KEY secret is not configured"
            exit 1
          }

          $keyPath = Join-Path $sshDir "id_deploy"

          # Normalize line endings and ensure proper format
          $keyContent = $keyContent.Replace("`r`n", "`n").Replace("`r", "`n")

          # Ensure key ends with a newline
          if (!$keyContent.EndsWith("`n")) {
            $keyContent += "`n"
          }

          # Write with Unix line endings (LF only)
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          [System.IO.File]::WriteAllText($keyPath, $keyContent, $utf8NoBom)

          # Set proper permissions (Windows)
          $acl = Get-Acl $keyPath
          $acl.SetAccessRuleProtection($true, $false)
          $accessRule = New-Object System.Security.AccessControl.FileSystemAccessRule(
            $env:USERNAME, "FullControl", "Allow"
          )
          $acl.SetAccessRule($accessRule)
          Set-Acl -Path $keyPath -AclObject $acl

          Write-Host "SSH key prepared at: $keyPath"

      - name: Preflight connectivity check
        shell: powershell
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
        run: |
          if (!$env:SERVER_HOST) {
            Write-Error "SERVER_HOST secret is not configured"
            exit 1
          }

          Write-Host "Testing connection to $env:SERVER_HOST:22..."
          $connectionTest = Test-NetConnection $env:SERVER_HOST -Port 22 -WarningAction SilentlyContinue

          if (!$connectionTest.TcpTestSucceeded) {
            Write-Error "Cannot reach $env:SERVER_HOST:22 from runner. Check:"
            Write-Error "   - Is the network/VPN connection active?"
            Write-Error "   - Is the SERVER_HOST IP correct?"
            Write-Error "   - Is SSH service running on the target server?"
            Write-Error "   - Are firewall rules configured correctly?"
            exit 1
          }

          Write-Host "Connection to $env:SERVER_HOST:22 successful"

      - name: Upload deploy bundle
        shell: powershell
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
        run: |
          if (!$env:SERVER_USER) {
            Write-Error "SERVER_USER secret is not configured"
            exit 1
          }

          $sshKeyPath = Join-Path $env:USERPROFILE ".ssh\id_deploy"
          $deployPath = "${{ steps.env.outputs.DEPLOY_PATH }}"

          # First, ensure the deploy directory exists on the remote server
          $sshDirArgs = @(
            "-i", $sshKeyPath
            "-p", "22"
            "-o", "StrictHostKeyChecking=no"
            "-o", "UserKnownHostsFile=NUL"
            "$env:SERVER_USER@$env:SERVER_HOST"
            "mkdir -p $deployPath"
          )

          Write-Host "Creating deploy directory on remote server..."
          & ssh @sshDirArgs

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Failed to create deploy directory"
            exit 1
          }

          # Upload deploy.zip
          $scpArgs = @(
            "-i", $sshKeyPath
            "-P", "22"
            "-o", "StrictHostKeyChecking=no"
            "-o", "UserKnownHostsFile=NUL"
            ".\deploy.zip"
            "$env:SERVER_USER@$env:SERVER_HOST`:$deployPath/deploy.zip"
          )

          Write-Host "Uploading deploy.zip to $env:SERVER_USER@$env:SERVER_HOST..."
          & scp @scpArgs

          if ($LASTEXITCODE -ne 0) {
            Write-Error "SCP upload failed with exit code $LASTEXITCODE"
            exit 1
          }

          Write-Host "Deploy bundle uploaded successfully"

      - name: Deploy to ${{ steps.env.outputs.ENV_NAME }}
        shell: powershell
        env:
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_USER: ${{ secrets.SERVER_USER }}
          BRANCH: ${{ github.ref }}
        run: |
          $envName = "${{ steps.env.outputs.ENV_NAME }}"
          $deployPath = "${{ steps.env.outputs.DEPLOY_PATH }}"

          # Create deployment script
          $deployLines = @(
            "#!/bin/bash",
            "set -euxo pipefail",
            "",
            "echo 'Starting deployment to $envName...'",
            "echo 'Deploy path: $deployPath'",
            "",
            "cd $deployPath || { echo 'ERROR: Cannot change to deploy directory'; exit 1; }",
            "",
            "echo 'Extracting deploy bundle...'",
            "tar -xzf deploy.zip",
            "",
            "echo 'Project structure:'",
            "ls -la",
            "",
            "echo 'Checking for docker-compose.yml...'",
            "if [ -f server/docker-compose.yml ]; then",
            "  echo 'Found docker-compose.yml in server folder'",
            "  cd server",
            "elif [ -f docker-compose.yml ]; then",
            "  echo 'Found docker-compose.yml in root'",
            "else",
            "  echo 'ERROR: docker-compose.yml not found'",
            "  exit 1",
            "fi",
            "",
            "echo 'Current directory:'",
            "pwd",
            "ls -la",
            "",
            "echo 'Stopping and removing existing containers...'",
            "docker-compose down --remove-orphans || true",
            "docker rm -f wfm-awx-fastapi 2>/dev/null || true",
            "",
            "echo 'Starting services...'",
            "docker-compose up --build -d",
            "",
            "sleep 10",
            "",
            "echo 'Running containers:'",
            "docker ps",
            "",
            "echo 'Container logs:'",
            "docker-compose logs --tail=20",
            "",
            "echo 'Successfully deployed to $envName'"
          )

          $deployScript = $deployLines -join "`n"
          $sshKeyPath = Join-Path $env:USERPROFILE ".ssh\id_deploy"

          # Create temporary script file
          $tempScript = Join-Path $env:TEMP "deploy-script.sh"

          # Write with Unix line endings
          $utf8NoBom = New-Object System.Text.UTF8Encoding($false)
          [System.IO.File]::WriteAllText($tempScript, $deployScript, $utf8NoBom)

          # Upload the script
          $scpScriptArgs = @(
            "-i", $sshKeyPath
            "-P", "22"
            "-o", "StrictHostKeyChecking=no"
            "-o", "UserKnownHostsFile=NUL"
            $tempScript
            "$env:SERVER_USER@$env:SERVER_HOST`:~/deploy-script.sh"
          )

          Write-Host "Uploading deployment script..."
          & scp @scpScriptArgs

          if ($LASTEXITCODE -ne 0) {
            Write-Error "Script upload failed"
            exit 1
          }

          # Execute the script
          $sshArgs = @(
            "-i", $sshKeyPath
            "-p", "22"
            "-o", "StrictHostKeyChecking=no"
            "-o", "UserKnownHostsFile=NUL"
            "$env:SERVER_USER@$env:SERVER_HOST"
            "chmod +x ~/deploy-script.sh && ~/deploy-script.sh && rm ~/deploy-script.sh"
          )

          Write-Host "Executing deployment on remote server..."
          Write-Host "----------------------------------------"
          & ssh @sshArgs
          $deployExitCode = $LASTEXITCODE

          # Clean up local temp file
          Remove-Item -Path $tempScript -Force -ErrorAction SilentlyContinue

          if ($deployExitCode -ne 0) {
            Write-Host "----------------------------------------"
            Write-Error "Deployment failed with exit code $deployExitCode"
            Write-Host "Fetching deployment logs for troubleshooting..."
            
            # Try to get more details from the server
            $logArgs = @(
              "-i", $sshKeyPath
              "-p", "22"
              "-o", "StrictHostKeyChecking=no"
              "-o", "UserKnownHostsFile=NUL"
              "$env:SERVER_USER@$env:SERVER_HOST"
              "cd $deployPath && docker-compose logs --tail=50 2>&1 || echo 'No logs available'"
            )
            & ssh @logArgs
            
            exit 1
          }

          Write-Host "----------------------------------------"
          Write-Host "Deployment completed successfully!"

      - name: Cleanup SSH key
        if: always()
        shell: powershell
        run: |
          Remove-Item -Path "$env:USERPROFILE\.ssh\id_deploy" -ErrorAction SilentlyContinue
          Write-Host "SSH key cleaned up"
